# Site settings
title: Christian de Fries Danielsen
email: me@cdanielsen.dk
description: > # this means to ignore newlines until "baseurl:"
  Go away.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cdanielsen.dk" # the base hostname & protocol for your site
twitter_username: chribsen
github_username:  chribsen

# Build settings
markdown: kramdown
